version: "3"

services:
  # ホストを監視用の Node Exporter
  node_exporter:
    tty: true
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
    networks:
      - br_prom_network
    restart: always

networks:
  br_prom_network:
    external: true
